title:            
description:      My academic webpage.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://c-s-li.github.io

# Owner/author information
owner:
  name:           Chun Sheng LI
  avatar:         20190825232007 - CV pic2.jpg
  bio:            <p>Assistant Professor</p>
                  <p>Department of Decision Sciences</p>
                  <p>School of Business</p>
                  <p>Macau University of Science and Technology</p>
  email:          csli(at)must.edu.mo
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  #twitter: jponttuset
  #linkedin: salman-hameed-khan-12184128
  google_scholar: YKSyFhYAAAAJ
  #google_plus: 113718226018314522413
  #github: jponttuset
  
